version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ssafy_orai_api_1
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true



