services:
  api:
    build:
      context: .
    container_name: ssafy_orai_api_1
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - mysql
      - redis

networks:
  mynetwork:
    external: true