services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ssafy_orai_api_1
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_LOCATION=/config/application.yml
    volumes:
      - ./config:/config
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true



