services:
  api:
    build:
      context: .
    container_name: ssafy_orai_api_1
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_LOCATION=/config/application.yml
    volumes:
      - ./config:/backend/config
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true



