name: kkulkkulk
description: 운동 기록 앱
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0  
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5
  go_router: ^13.0.1
  sign_button: ^2.0.6
  pretty_animated_buttons: ^0.0.2
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.5.1  
  geolocator: ^13.0.2
  logger: ^2.5.0
  big_decimal: ^0.5.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  intl: ^0.19.0  
  camera: ^0.11.1
  video_player: ^2.8.1
  image_picker: ^0.8.4+4
  path_provider: ^2.1.5
  saver_gallery: ^3.0.2
  permission_handler: ^11.0.1
  flutter_colorpicker: ^1.1.0
  fc_native_video_thumbnail: ^0.17.2
  video_compress: ^3.1.3
  file_picker: ^6.1.1
  table_calendar: ^3.1.3
  fl_chart: ^0.70.2
  riverpod_annotation: ^2.3.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/oauth/
    - assets/images/
    - assets/images/tier/
    - assets/images/default_profile.png

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardGOV-Regular.otf
        - asset: assets/fonts/PretendardGOV-Bold.otf
          weight: 700
